### ISSUE TITLE
Cannot install via pip install

### ISSUE THREAD

**Issue by m-d-grunnill** [ukhsa-collaboration/pygom#107]
Cannot install via ``pip install pygom``. I get following list of errors:

``
 writing manifest file 'pygom.egg-info\SOURCES.txt'
      C:\Users\mdgru\.conda\envs\pygom\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pygom.model' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'pygom.model' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'pygom.model' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'pygom.model' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      C:\Users\mdgru\.conda\envs\pygom\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pygom.approximate_bayesian_computation' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'pygom.approximate_bayesian_computation' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'pygom.approximate_bayesian_computation' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'pygom.approximate_bayesian_computation' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      C:\Users\mdgru\.conda\envs\pygom\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'pygom.data' as data is deprecated, please list it in `packages`.
          !!

          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'pygom.data' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'pygom.data' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'pygom.data' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.

      !!

        check.warn(importable)
      copying pygom\model\_tau_leap.pyx -> build\lib.win-amd64-cpython-310\pygom\model
      creating build\lib.win-amd64-cpython-310\pygom\approximate_bayesian_computation
      copying pygom\approximate_bayesian_computation\__init__.py -> build\lib.win-amd64-cpython-310\pygom\approximate_bayesian_computation
      copying pygom\approximate_bayesian_computation\approximate_bayesian_computation.py -> build\lib.win-amd64-cpython-310\pygom\approximate_bayesian_computation
      creating build\lib.win-amd64-cpython-310\pygom\data
      copying pygom\data\eg1.json -> build\lib.win-amd64-cpython-310\pygom\data
      copying pygom\model\_tau_leap.c -> build\lib.win-amd64-cpython-310\pygom\model
      copying pygom\loss\.gitignore -> build\lib.win-amd64-cpython-310\pygom\loss
      running build_ext
      skipping 'pygom/model\_tau_leap.c' Cython extension (up-to-date)
      building 'pygom.model._tau_leap' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\pygom
      creating build\temp.win-amd64-cpython-310\Release\pygom\model
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\mdgru\.conda\envs\pygom\lib\site-packages\numpy\core\include -IC:\Users\mdgru\.conda\envs\pygom\include -IC:\Users\mdgru\.conda\envs\pygom\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcpygom/model\_tau_leap.c /Fobuild\temp.win-amd64-cpython-310\Release\pygom/model\_tau_leap.obj
      _tau_leap.c
      C:\Users\mdgru\.conda\envs\pygom\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      pygom/model\_tau_leap.c(18375): error C2105: '++' needs l-value
      pygom/model\_tau_leap.c(18377): error C2105: '--' needs l-value
      pygom/model\_tau_leap.c(18686): error C2105: '++' needs l-value
      pygom/model\_tau_leap.c(18688): error C2105: '--' needs l-value
      pygom/model\_tau_leap.c(18936): error C2105: '++' needs l-value
      pygom/model\_tau_leap.c(18938): error C2105: '--' needs l-value
      pygom/model\_tau_leap.c(22097): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pygom

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
``

**Comment by m-d-grunnill** [comment]
Installation via downloading from github and then using ``python setup.py install`` works.

**Comment by twomagpi** [comment]
Installation should now be significantly easier following our update to the build process for #114 . On Windows and Linux, in most cases, pip should install from binary wheels. negating the problems above
