### ISSUE TITLE
Stochastic simulation could do with a break clause if specified populations reach 0.

### ISSUE THREAD

**Issue by MGrunnill** [ukhsa-collaboration/pygom#30]
Depending on the nature of the stochastic simulation if certain class/es have gone  extinct it is not necessary to continue running the simulation. A break clause could be added to stop a simulation if the population in certain class/es reached 0. 

Within the module `simulate.py` following additions could be made: 

- The function `simulate_jump` could take the optional argument `stop_at_extinction_of`. This argument would take a list of indexes of state variables, the default argument would be an empty list.

- Before the while loop within the function `_jump` the code `extinction_clause = False` could be added.

- The while argument within the function  `_jump` would become `while t < finalT and extinction_clause == False:`.

- At the end of the while loop within the function  `_jump` the following code could be added:  
```python
if len(self.stop_at_extinction_of)!=0:
    if sum(x[self.stop_at_extinction_of]) ==0:
        extinction_clause = True
```

- After the while loop  within the function  `_jump` there would have to be some post prossesing. Filling each of the time steps after extinction of the np.arrays `xList` and `tList` with either NA values or a string stating the selected population/s had gone extinct.

**Comment by twomagpi** [comment]
Would halting occur when any class in the list went extinct or only if all classes went extinct?

I can think of cases where both would be helpful. How should the api look to allow eaither case?

Are there likely to be issues induced by having response variables of differing lengths from different runs?

**Comment by twomagpi** [comment]
Might be possible to make this a bit more generic and introduce stopping conditions for stochastic simulations.
Perhaps the simulate api should accept an interable of stopping condition objects. These objects would then have state and conditional attributes. I.e. for the case outlined in @MGrunnill 's initial issue these might be  'S' and '<= 0'. There is also the thought that the condition itself should perhaps be an equation (like the transition objects) so that you could set up conditions like 'S' '< 2 R' to make this as flexible as possible.

**Comment by twomagpi** [comment]
With this the answer to the inital questions would be:
* The user has discression to choose what classes are important to them (and the condition is also under user control)
* The API is clean (just an additional list of well-controlled objects)
* As turning this on is under user control they would be expected to handle the outcome of early termination of the simulation in their own code.

**Comment by twomagpi** [comment]
After consideration this significantly complicates the (already complicated) code. so will not happen at this stage.
