### ISSUE TITLE
PyGOM and a function no longer within Scipy

### ISSUE THREAD

**Issue by MGrunnill** [ukhsa-collaboration/pygom#39]
Just in case you update scipy note that a function seems to be lost in later version. This causes the error below when importing PyGOM. I found that reverting scipy to version  1.3.2 fixed this issue.
scipy.special.cython_special does not export expected C function __pyx_fuse_0pdtr

**Comment by twomagpi** [comment]
I think this relates to the fact that the C code from Cython is preshipped. Rebuilding the C code against the new version of the library may well work round this issue.

There mighht be a better of supplying the C code. Have to work round not everybody having Cython installed.

**Comment by twomagpi** [comment]
New build process for #114 should fix this.
