### ISSUE TITLE
List of required packages needs updating in readme and yml file. Also prerequisite of Microsofts C++ compiler could do with a mention.

### ISSUE THREAD

**Issue by m-d-grunnill** [ukhsa-collaboration/pygom#55]
The list is not the same between the yml file and the readme file.
A note about requiring Microsofts C++ compiler from https://visualstudio.microsoft.com/visual-cpp-build-tools/ may also be required in the readme.

**Comment by twomagpi** [comment]
Updated documentation for source installs http://ukhsa-collaboration.github.io/pygom/md/getting_started.html and have moved from a requirements file to a pyproject.toml for #114
