### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hareball90** [ukhsa-collaboration/pygom#70]
In addition to deprecation warnings, after running `conda install -c conda-forge gcc` to solve `gcc not found` I get the error:
`error: command '/home/.../miniconda3/envs/pygom-test/bin/gcc' failed with exit code 1` 

Other tickets also report install issues. 

Edit: this error is on hpc

**Comment by HWilliams-PHE** [comment]
Error on local machine (using VS Code) without installing gcc

`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2`

**Comment by twomagpi** [comment]
The new wheel builds make this massively simpler for Windows and Linux without pre-installed compilers.

  pip install pygom

now 'just works' for #114
