### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by hareball90** [ukhsa-collaboration/pygom#73]
Contributor guidelines should include:
- PR template
- stating what acknowledgement/authorship a contributor is entitled to

**Comment by HWilliams-PHE** [comment]
by contributing, acknowledge that they are assigning copyright to us so we can continue to maintain package, always be licensed under gpl2

reviewer to add contributor to readme

**Comment by hareball90** [comment]
This all-contrbutors looks like it could help? https://github.com/all-contributors/all-contributors

**Comment by twomagpi** [comment]
Partially resolved by #76

**Comment by twomagpi** [comment]
I think all-contributors is probably to much technology to solve the problem of adding people to the README. Can revisit if the project becomes bigger.
