### ISSUE TITLE
Branding guidelines

### ISSUE THREAD

**Issue by hareball90** [ukhsa-collaboration/pygom#74]
Can we use a logo? 

Can we create a theme using branding palette?

**Comment by hareball90** [comment]
created a logo using corporate colours, and no need to use official branding

default jupyter theme is fine for now

**Comment by hareball90** [comment]
I think this is now fixed/irrelevant, but check you're happy with the colour theme throughout before closing.

**Comment by twomagpi** [comment]
Happy with the new colours :-)
