### ISSUE TITLE
cython error

### ISSUE THREAD

**Issue by hareball90** [ukhsa-collaboration/pygom#95]
@jontycarruthersphe had an install error

on doing `python setup.py install`

error message: 
File "/home/phe.gov.uk/jonathan.carruthers/pygom/pygom/pygom/model/stochastic_simulation.py", line 18, in <module>
    from ._tau_leap import _cy_test_tau_leap_safety
ModuleNotFoundError: No module named 'pygom.model._tau_leap'

**Comment by hareball90** [comment]
solution appears to be to comment out line 18 in pygom/model/stochastic_simulation.py

unsure about the impact of removing this line

**Comment by twomagpi** [comment]
Done. Build system updated to provide wheels for Windows in #114 that should mitigate this too.
