### ISSUE TITLE
warning in windows build of jupyterbook - asyncio

### ISSUE THREAD

**Issue by hareball90** [ukhsa-collaboration/pygom#97]
RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.

see issue and proposed solution - https://github.com/nteract/papermill/issues/515#issuecomment-645992905

**Comment by twomagpi** [comment]
Think this is now resolved for #114
